INSERT INTO categories (name) VALUES
('Breakfast'),
('Brunch'),
('Lunch'),
('Dinner'),
('Snacks'),
('Appetizers / Starters'),
('Main Courses'),
('Side Dishes'),
('Desserts'),
('Baked Goods'),
('Street Food'),
('Fast Food'),
('Beverages / Drinks'),
('Smoothies & Juices'),
('Soups & Stews'),
('Salads'),
('Sandwiches & Wraps'),
('Rice Dishes'),
('Pasta & Noodles'),
('Grilled Foods'),
('Fried Foods'),
('Seafood'),
('Meat Dishes'),
('Vegetarian Dishes'),
('Vegan Dishes'),
('Gluten-Free Foods'),
('Low-Carb / Keto'),
('Healthy Meals'),
('Comfort Foods'),
('Traditional Foods'),
('Kids’ Meals'),
('Party Foods'),
('Holiday / Festive Foods');
