INSERT INTO countries (name, region) VALUES
('Kenya','Africa'),
('Nigeria','Africa'),
('Ethiopia','Africa'),
('Ghana','Africa'),
('South Africa','Africa'),
('Tanzania','Africa'),
('Uganda','Africa'),
('Morocco','Africa'),
('Egypt','Africa'),

('China','Asia'),
('India','Asia'),
('Japan','Asia'),
('Thailand','Asia'),
('South Korea','Asia'),
('Vietnam','Asia'),
('Indonesia','Asia'),
('Philippines','Asia'),

('Lebanon','Middle East'),
('Turkey','Middle East'),
('Iran','Middle East'),
('Israel','Middle East'),

('Italy','Europe'),
('France','Europe'),
('Spain','Europe'),
('United Kingdom','Europe'),
('Germany','Europe'),
('Greece','Europe'),

('United States','North America'),
('Mexico','North America'),
('Canada','North America'),
('Brazil','South America'),
('Argentina','South America'),

('Australia','Oceania'),
('International','Global');
